[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/add"
  to = "/.netlify/functions/add"
  status = 200

[[redirects]]
  from = "/api/update"
  to = "/.netlify/functions/update"
  status = 200

[[redirects]]
  from = "/api/delete"
  to = "/.netlify/functions/delete"
  status = 200

[[redirects]]
  from = "/api/admin/categories"
  to = "/.netlify/functions/admin-categories"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin-category/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/get/:splat"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"