[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run railway"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[environments]
production = {
  variables = {
    NODE_ENV = "production",
    BOT_TOKEN = "${{BOT_TOKEN}}",
    ADMIN_USER_ID = "${{ADMIN_USER_ID}}",
    ACCESS_CODES = "${{ACCESS_CODES}}"
  }
}

development = {
  variables = {
    NODE_ENV = "development"
  }
}