[build]
builder = "nixpacks"

[deploy]
startCommand = "node bot-production.js"
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
railwayTomlVersion = 2

[environments]
production = {
  variables = {
    NODE_ENV = "production",
    BOT_TOKEN = "${{BOT_TOKEN}}",
    ADMIN_USER_ID = "${{ADMIN_USER_ID}}",
    ACCESS_CODES = "${{ACCESS_CODES}}",
    DISABLE_BOT = "false"
  }
}

development = {
  variables = {
    NODE_ENV = "development",
    DISABLE_BOT = "true"
  }
}